#!/bin/bash
out_str="out"
txt_str=".txt"
tp_min=$1
tp_max=$2
dfc_min=$3
dfc_max=$4
for ((dfc=$dfc_min; dfc<=$dfc_max; dfc=$dfc+4))
	do
		this_out_name="$tp_min$out_str$dfc$txt_str";
		nohup ./MAC.exe $tp_min $tp_max $dfc $dfc >$this_out_name &
	done
